// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-apps.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function anonClient() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_apps_default = defineTool({
  name: "list_apps",
  title: "List apps",
  description: "List approved apps in the OpenApp directory. Optionally filter by search text, category id, featured, popular, or pricing model.",
  inputSchema: {
    search: z.string().optional().describe("Case-insensitive text to match in name or tagline."),
    category_id: z.string().uuid().optional().describe("Filter by category UUID."),
    featured: z.boolean().optional().describe("Only featured apps."),
    popular: z.boolean().optional().describe("Only popular apps."),
    pricing_model: z.enum(["free", "paid"]).optional(),
    limit: z.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category_id, featured, popular, pricing_model, limit }) => {
    let query = anonClient().from("apps").select(
      "id, name, tagline, description, logo_url, website_url, category_id, tags, is_featured, is_popular, average_rating, ratings_count, views_count, pricing_model, price_amount, developer_name, created_at"
    ).eq("status", "approved").order("views_count", { ascending: false }).limit(limit);
    if (search) query = query.or(`name.ilike.%${search}%,tagline.ilike.%${search}%`);
    if (category_id) query = query.eq("category_id", category_id);
    if (featured !== void 0) query = query.eq("is_featured", featured);
    if (popular !== void 0) query = query.eq("is_popular", popular);
    if (pricing_model) query = query.eq("pricing_model", pricing_model);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { apps: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-app.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function anonClient2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_app_default = defineTool2({
  name: "get_app",
  title: "Get app details",
  description: "Fetch full details for a single approved app in the OpenApp directory by its UUID.",
  inputSchema: {
    id: z2.string().uuid().describe("App UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = anonClient2();
    const { data: app, error } = await supabase.from("apps").select("*").eq("id", id).eq("status", "approved").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!app) return { content: [{ type: "text", text: "App not found." }], isError: true };
    const { data: screenshots } = await supabase.from("screenshots").select("id, image_url, display_order").eq("app_id", id).order("display_order", { ascending: true });
    const payload = { ...app, screenshots: screenshots ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
function anonClient3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List all app categories in the OpenApp directory.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const { data, error } = await anonClient3().from("categories").select("id, name, icon, description").order("name", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function anonClient4() {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_blog_posts_default = defineTool4({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published blog posts from the OpenApp blog.",
  inputSchema: {
    search: z3.string().optional().describe("Case-insensitive text to match in title."),
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }) => {
    let query = anonClient4().from("blog_posts").select("id, slug, title, excerpt, cover_image_url, published_at, tags").eq("status", "published").order("published_at", { ascending: false }).limit(limit);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "openapp-mcp",
  title: "OpenApp Directory",
  version: "0.1.0",
  instructions: "Public tools for browsing the OpenApp directory: search apps, fetch app details, list categories, and read published blog posts. All data returned is intentionally public.",
  tools: [list_apps_default, get_app_default, list_categories_default, list_blog_posts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
